#!/bin/sh

export IMAGE_NAME=of-7.sif

singularity exec $IMAGE_NAME surfaceFeatures
singularity exec $IMAGE_NAME blockMesh
singularity exec $IMAGE_NAME decomposePar -copyZero

mpirun -np 4 singularity exec $IMAGE_NAME snappyHexMesh -overwrite parallel
mpirun -np 4 singularity exec $IMAGE_NAME potentialFoam -parallel
mpirun -np 4 singularity exec $IMAGE_NAME simpleFoam -parallel

singularity exec $IMAGE_NAME reconstructParMesh -constant
singularity exec $IMAGE_NAME reconstructPar -latestTime

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
